### PR TITLE
Updating to Ionic 3.13.2

### PR DESCRIPTION
**Pull request by dmastag**
Looks like a Bug, thats why there is a quick update

### CODE REVIEW

**Comment by dmastag** [comment]
This isn't working
turns out there is this problem with oracle-java8-installer as per 
https://ubuntuforums.org/showthread.php?t=2374686

Any idea about this?

**Comment by MichaelBitard** [comment]
We could wait for the webupd8team to update their repository?

**Comment by dmastag** [comment]
Looks like its updated, could you try again ?

**Comment by MichaelBitard** [comment]
Building ;)

**Comment by dmastag** [comment]
Awesome, working !

image

Don't forget to update the latest one 😃

**Comment by MichaelBitard** [comment]
Done too :)

**Pull request merged**
