### PR TITLE
Update Ionic and Node to latest

### PR DESCRIPTION
**Pull request by dmastag**

### CODE REVIEW

**Comment by MichaelBitard** [comment]
Thanks!

**Comment by dmastag** [comment]
Great, how long does it usually take until the docker image is updated?
Just tried to `docker pull agileek/ionic-framework` but it says I am still on the latest.

**Comment by MichaelBitard** [comment]
Ho, it seems that the build failed because when we do `ionic start myApp sidemenu` it now asks for confirmation...

**Comment by dmastag** [comment]
That should be fixed in #13

**Comment by MichaelBitard** [comment]
You should be able to play with agileek/ionic-framework:3.9.2

**Pull request merged**
